### ISSUE TITLE
No permissions on Skyfactory 3 after the update.

### ISSUE THREAD

**Issue by theSman139** [badgernz/wiki#21]
No commands work... cant even go to the hub or use global chat.
Nothing works other then /help.

IGN- theSman139

Hope its not a pain to try and fix.

**Comment by badgernz** [comment]
sorry about that, all fixed now. 
Next time please use either the ingame ticket system through the 1.10 hub or any 1.7.10 server
or use the website forums, staff are also available on teamspeak.
Thanks
